version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    env_file:
      - dev.env
      
  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    env_file:
      - dev.env
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  app:
    build: .
    container_name: app
    env_file:
      - dev.env
    ports:
      - "8080:8080"
    depends_on:
      - broker